services:
  redis1:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: redis:patchednetstat
    cap_add:
    - sys_resource
    platform: linux/amd64
    ports:
     - "7379:6379"
     - "9070:8070"
     - "9443:8443"
     - "10443:9443"
     - "12000-12001:12000-12001"
    networks:
      fromscratch:
        ipv4_address: "172.64.1.2"
    # ports:
    #   - "8000:80"
    volumes:
      - ./redis-1:/redis
  redis2:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: redis:patchednetstat
    cap_add:
    - sys_resource
    platform: linux/amd64
    ports:
     - "7390:6379"
     - "9071:8070"
     - "9444:8443"
     - "10444:9443"
     - "12002-12003:12000-12001"
    networks:
      fromscratch:
        ipv4_address: "172.64.1.3"
    # ports:
    #   - "8000:80"
    volumes:
      - ./redis-2:/redis
  redis3:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: redis:patchednetstat
    cap_add:
    - sys_resource
    platform: linux/amd64
    ports:
     - "7381:6379"
     - "9072:8070"
     - "9445:8443"
     - "10445:9443"
     - "12004-12005:12000-12001"
    networks:
      fromscratch:
        ipv4_address: "172.64.1.4"
    # ports:
    #   - "8000:80"
    volumes:
      - ./redis-3:/redis

networks:
  fromscratch:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
       -
        subnet: 172.64.1.0/24
        gateway: 172.64.1.1
